name: Take screenshot with Percy

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
      - name: Install dependencies
        run: npm install @percy/cli
        
      - name: Take Percy snapshot
        run: npx percy snapshot https://hodat140600.github.io/My-Info/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          
      # Note: you would need to sign up for Percy and add your token to GitHub secrets
