name: Take screenshot of CV

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Take screenshot
      uses: flameddd/screenshots-ci-action@v1.1.0
      with:
        url: https://hodat140600.github.io/My-Info/
        width: 1280
        height: 800
        fullPage: true
        output: cv-preview.png
    - name: Commit screenshot
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add cv-preview.png
        git commit -m "Update CV preview" || echo "No changes to commit"
        git push
