name: Update CV Preview
on:
  repository_dispatch:
    types: [my-info-updated]
  schedule:
    - cron: '0 0 * * *'  # Sửa lỗi cú pháp cron
  workflow_dispatch:  # Allow manual triggering
jobs:
  update_screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Lấy toàn bộ lịch sử commit
      
      - name: Git pull to get latest changes
        run: git pull origin $(git branch --show-current)
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Puppeteer
        run: npm install puppeteer@10.0.0  # Chỉ định phiên bản cụ thể
        
      - name: Create screenshots directory if it doesn't exist
        run: mkdir -p screenshots
        
      - name: Take screenshot
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          
          (async () => {
            const browser = await puppeteer.launch({
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            await page.setViewport({width: 1200, height: 800});
            
            // Tắt cache để đảm bảo lấy nội dung mới
            await page.setCacheEnabled(false);
            
            // Thêm timeout dài hơn và đợi trang tải hoàn toàn
            await page.goto('https://hodat140600.github.io/My-Info/', {
              waitUntil: 'networkidle0',
              timeout: 60000
            });
            
            // Sử dụng setTimeout thay vì waitForTimeout
            await page.evaluate(() => new Promise(resolve => setTimeout(resolve, 3000)));
            
            await page.screenshot({path: 'screenshots/cv-preview.png', fullPage: true});
            await browser.close();
          })()
          "
          
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet screenshots/cv-preview.png || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add screenshots/cv-preview.png
          git commit -m "Update CV preview [skip ci]"
          git push
