name: Take screenshot of CV

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}  # Use your secret name here
    - name: Take screenshot
      uses: flameddd/screenshots-ci-action@v1.1.0
      with:
        url: https://hodat140600.github.io/My-Info/
        width: 1280
        height: 800
        fullPage: true
        output: screenshots/cv-preview.png
    - name: Commit and push if changed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add screenshots/cv-preview.png
        git commit -m "Update CV preview" || echo "No changes to commit"
        git push https://${{ secrets.PAT }}@github.com/hodat140600/hodat140600.git
