name: Take screenshot of CV

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install Puppeteer
      run: npm install puppeteer
    
    - name: Take screenshot with Puppeteer
      run: |
        node -e "
        const puppeteer = require('puppeteer');
        
        (async () => {
          const browser = await puppeteer.launch({
            executablePath: 'google-chrome',
            args: ['--no-sandbox', '--disable-setuid-sandbox']
          });
          const page = await browser.newPage();
          await page.setViewport({ width: 1280, height: 1024 });
          await page.goto('https://hodat140600.github.io/My-Info/', { waitUntil: 'networkidle0' });
          await page.screenshot({ path: 'cv-preview.png', fullPage: true });
          await browser.close();
        })();
        "
      
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update CV preview"
        git push
