name: Update CV Preview

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate preview
        uses: sindresorhus/pageres-cli-action@v1
        with:
          args: https://hodat140600.github.io/My-Info/ 800x600 --filename=cv-preview
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add cv-preview.png
          git commit -m "Update CV preview" || echo "No changes to commit"
          git push
